//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fd_analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fd_analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate error: {0}.
        /// </summary>
        internal static string AggregateMessageFormat {
            get {
                return ResourceManager.GetString("AggregateMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor.
        /// </summary>
        internal static string ConstructorCategory {
            get {
                return ResourceManager.GetString("ConstructorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty constructor should not contain statements..
        /// </summary>
        internal static string EmptyConstructorDescription {
            get {
                return ResourceManager.GetString("EmptyConstructorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating empty constructor.
        /// </summary>
        internal static string EmptyConstructorTitle {
            get {
                return ResourceManager.GetString("EmptyConstructorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-empty constructors should be private..
        /// </summary>
        internal static string PrivateConstructorDescription {
            get {
                return ResourceManager.GetString("PrivateConstructorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating non-private constructor.
        /// </summary>
        internal static string PrivateConstructorTitle {
            get {
                return ResourceManager.GetString("PrivateConstructorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate &apos;Apply&apos; methods should always be public..
        /// </summary>
        internal static string PublicApplyMethodsDescription {
            get {
                return ResourceManager.GetString("PublicApplyMethodsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating non-public Apply.
        /// </summary>
        internal static string PublicApplyMethodsTitle {
            get {
                return ResourceManager.GetString("PublicApplyMethodsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty constructor should be public.
        /// </summary>
        internal static string PublicConstructorDescription {
            get {
                return ResourceManager.GetString("PublicConstructorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating empty constructor.
        /// </summary>
        internal static string PublicConstructorTitle {
            get {
                return ResourceManager.GetString("PublicConstructorTitle", resourceCulture);
            }
        }
    }
}
